При загрузке страницы - блоки выбора ZipCode (по индексу, названиям, либо координатам или геопозиции)
При вводе данных autocomplete  - не больше 10?
Выбранные объекты попадают в список Zip - список можно очистить, удалять элементы, не больше 5 объектов
При наличии в списке элементов - активны кнопки с отчетами
Интерфейс:
  Интересные факты:
    Рандомно показывают выборки
Детализация:
  Регион:
    Данные:
      Штат
      Округ
      Код местности
      Район страны
Отчеты:
  Местность:
    Данные:
      Площадь земли
      Площадь воды
      Высота над уровнем моря
  Бытовая статистика:
    Данные:
      Число домохозяйств
      Средняя число человек
      Уровень дохода
      Уровень дохода по градациям (бедный<25<50<100<200<богатый)
  Образование:
    Данные:
      Процент закончивших школу
      Процент закончивших институт
  Бизнес:
    Данные:
      Количество предприятий
      Количество рабочих
      Количество расчетных листов за год/квартал
  Преступления:
    Данные:
      Количество насильственных преступлений
      Количество убийств
      Количество изнасилований
      Количество ограблений
      Количество тяжелых нападений
      Количество преступлений с недвижимостью
      Количество взломов
      Количество случаев воровства
      Количество угонов
      Количество поджогов
  Рост населений:
    Данные:
      Рейтинги роста
  Средний возраст:
    Данные:
      Общий
      Мужчины
      Женщины
  Население:
    Данные:
      Всего людей
      Всего мужчин
      Всего женщин
      Разбиение по расам
      Разбиение по возрастам
  Семья:
    Данные:
      Среднее число сожителей
      Средний размер семьи
      Всего групп сожителей
      Всего семей
      Семей живущих с детьми до 18
      Семей где есть муж и жена
      Семей с мужем женой и детьми до 18
      Семьи где муж и дети
      Семьи где жена и дети
      Несемейных сожителей
      Одиноких жильцов
      Одиноких женшин
      Одиноких женщин 65+
      Одиноких мужчин
      Одиноких мужчин 65+
      Одиноких детей до 18
      Всего жил. единиц
      Занятых жил. единиц
      Единиц жилья на сдачу
      Единиц жилья на сдачу но свободных
      Единиц жилья на продажу но свободных
      Прочие единицы жилья     