# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20140205002612) do

  create_table "city_aliases", force: true do |t|
    t.integer "zip_code_id"
    t.string  "City"
    t.string  "CityAbbreviation"
  end

  add_index "city_aliases", ["City"], name: "index_city_aliases_on_City", using: :btree
  add_index "city_aliases", ["CityAbbreviation"], name: "index_city_aliases_on_CityAbbreviation", using: :btree
  add_index "city_aliases", ["zip_code_id"], name: "index_city_aliases_on_zip_code_id", using: :btree

  create_table "easy_zips", primary_key: "ZipCode", force: true do |t|
    t.float   "Longitude"
    t.float   "Latitude"
    t.string  "County"
    t.integer "state_id"
  end

  add_index "easy_zips", ["County"], name: "index_easy_zips_on_County", using: :btree
  add_index "easy_zips", ["Latitude"], name: "index_easy_zips_on_Latitude", using: :btree
  add_index "easy_zips", ["Longitude"], name: "index_easy_zips_on_Longitude", using: :btree
  add_index "easy_zips", ["state_id"], name: "index_easy_zips_on_state_id", using: :btree

  create_table "loaded_data", force: true do |t|
    t.integer "ZipCode"
    t.float   "Longitude"
    t.float   "Latitude"
    t.integer "ElevationAverageFeet"
    t.integer "Population"
    t.integer "WhitePopulation"
    t.integer "BlackPopulation"
    t.integer "HispanicPopulation"
    t.integer "AsianPopulation"
    t.integer "HawaiianPopulation"
    t.integer "IndianPopulation"
    t.integer "OtherPopulation"
    t.integer "MalePopulation"
    t.integer "FemalePopulation"
    t.float   "MedianAge"
    t.float   "MedianAgeMale"
    t.float   "MedianAgeFemale"
    t.float   "HouseholdsPerZipCode"
    t.float   "PersonsPerHousehold"
    t.float   "AverageHouseValue"
    t.float   "IncomePerHousehold"
    t.float   "IncomeBelowPoverty"
    t.float   "IncomeLessThan25"
    t.float   "IncomeBetween25to50"
    t.float   "IncomeBetween50to100"
    t.float   "IncomeBetween100to200"
    t.float   "IncomeGreater200"
    t.float   "EducationHighSchoolGraduate"
    t.float   "EducationBachelorOrGreater"
    t.string  "StateAbbreviation"
    t.string  "State"
    t.string  "CityAbbreviation"
    t.string  "AreaCode"
    t.string  "City"
    t.string  "County"
    t.string  "CountyFIPSCode"
    t.string  "StateFIPSCode"
    t.integer "TimeZone"
    t.boolean "IsDayLightSaving"
    t.boolean "IsZipCodeMultiCounty"
    t.string  "USRegion"
    t.string  "USDivision"
    t.string  "MSA"
    t.string  "MSAName"
    t.string  "PMSA"
    t.string  "PMSAName"
    t.string  "CSA"
    t.string  "CSAName"
    t.string  "CBSA"
    t.string  "CBSAName"
    t.string  "CBSADivision"
    t.string  "CBSAStatisticType"
    t.string  "CBSADivisionName"
    t.integer "TotalNumberOfBusinesses"
    t.integer "TotalNumberEmployees"
    t.integer "FirstQuarterPayroll"
    t.integer "AnnualPayroll"
    t.integer "ViolentCrime"
    t.integer "MurderAndManslaughter"
    t.integer "ForcibleRape"
    t.integer "Robbery"
    t.integer "AggravatedAssault"
    t.integer "PropertyCrime"
    t.integer "Burglary"
    t.integer "LarcenyTheft"
    t.integer "MotorVehicleTheft"
    t.integer "Arson"
    t.boolean "NearGayVillage"
    t.integer "GrowthRank"
    t.integer "GrowthHousingUnits2009"
    t.integer "GrowthHousingUnits2010"
    t.integer "GrowthIncreaseNumber"
    t.float   "GrowthIncreasePercentage"
    t.integer "DeliveryResidential"
    t.integer "DeliveryBusiness"
    t.integer "DeliveryTotal"
    t.float   "LandArea"
    t.float   "WaterArea"
    t.integer "PopulationEstimate"
    t.integer "SFDU"
    t.integer "MFDU"
    t.integer "PopulationUnder5"
    t.integer "Population5to9"
    t.integer "Population10to14"
    t.integer "Population15to19"
    t.integer "Population20to24"
    t.integer "Population25to29"
    t.integer "Population30to34"
    t.integer "Population35to39"
    t.integer "Population40to44"
    t.integer "Population45to49"
    t.integer "Population50to54"
    t.integer "Population55to59"
    t.integer "Population60to64"
    t.integer "Population65to69"
    t.integer "Population70to74"
    t.integer "Population75to79"
    t.integer "Population80to84"
    t.integer "Population85Plus"
    t.float   "PopulationMedian"
    t.integer "Population16Plus"
    t.integer "Population18Plus"
    t.integer "Population21Plus"
    t.integer "Population62Plus"
    t.integer "Population65Plus"
    t.integer "PopulationMale"
    t.integer "PopulationMaleUnder5"
    t.integer "PopulationMale5to9"
    t.integer "PopulationMale10to14"
    t.integer "PopulationMale15to19"
    t.integer "PopulationMale20to24"
    t.integer "PopulationMale25to29"
    t.integer "PopulationMale30to34"
    t.integer "PopulationMale35to39"
    t.integer "PopulationMale40to44"
    t.integer "PopulationMale45to49"
    t.integer "PopulationMale50to54"
    t.integer "PopulationMale55to59"
    t.integer "PopulationMale60to64"
    t.integer "PopulationMale65to69"
    t.integer "PopulationMale70to74"
    t.integer "PopulationMale75to79"
    t.integer "PopulationMale80to84"
    t.integer "PopulationMale85Plus"
    t.float   "PopulationMaleMedian"
    t.integer "PopulationMale16Plus"
    t.integer "PopulationMale18Plus"
    t.integer "PopulationMale21Plus"
    t.integer "PopulationMale62Plus"
    t.integer "PopulationMale65Plus"
    t.integer "PopulationFemale"
    t.integer "PopulationFemaleUnder5"
    t.integer "PopulationFemale5to9"
    t.integer "PopulationFemale10to14"
    t.integer "PopulationFemale15to19"
    t.integer "PopulationFemale20to24"
    t.integer "PopulationFemale25to29"
    t.integer "PopulationFemale30to34"
    t.integer "PopulationFemale35to39"
    t.integer "PopulationFemale40to44"
    t.integer "PopulationFemale45to49"
    t.integer "PopulationFemale50to54"
    t.integer "PopulationFemale55to59"
    t.integer "PopulationFemale60to64"
    t.integer "PopulationFemale65to69"
    t.integer "PopulationFemale70to74"
    t.integer "PopulationFemale75to79"
    t.integer "PopulationFemale80to84"
    t.integer "PopulationFemale85Plus"
    t.float   "PopulationFemaleMedian"
    t.integer "PopulationFemale16Plus"
    t.integer "PopulationFemale18Plus"
    t.integer "PopulationFemale21Plus"
    t.integer "PopulationFemale62Plus"
    t.integer "PopulationFemale65Plus"
    t.float   "AverageHouseholdSize"
    t.float   "AverageFamilySize"
    t.integer "TotalHouseholds"
    t.integer "FamilyHouseholds"
    t.integer "FamilyHouseholdsWithChildrenUnder18"
    t.integer "FamilyHouseholdsHusbandWifeFamily"
    t.integer "FamilyHouseholdsHusbandWifeFamilyChildrenUnder18"
    t.integer "FamilyHouseholdsMaleNoWife"
    t.integer "FamilyHouseholdsMaleNoWifeChildrenUnder18"
    t.integer "FamilyHouseholdFemaleNoHusband"
    t.integer "FamilyHouseholdFemaleNoHusbandChildrenUnder18"
    t.integer "NonFamilyHouseholds"
    t.integer "NonFamilyHouseholdsLivingAlone"
    t.integer "NonFamilyHouseholdsLivingAloneMale"
    t.integer "NonFamilyHouseholdsLivingAloneMale65plus"
    t.integer "NonFamilyHouseholdsLivingAloneFemale"
    t.integer "NonFamilyHouseholdsLivingAloneFemale65plus"
    t.integer "HouseholdsWithIndividualsUnder18"
    t.integer "HouseholdsWithIndividuals65plus"
    t.integer "TotalHousingUnits"
    t.integer "OccupiedHousingUnits"
    t.integer "VacantHousingUnits"
    t.integer "VacantHousingUnitsForRent"
    t.integer "VacantHousingUnitsRentedNotOccupied"
    t.integer "VacantHousingUnitsForSale"
    t.integer "VacantHousingUnitsSoldNotOccupied"
    t.integer "VacantHousingUnitsForSeasonalOccasionalUse"
    t.integer "VacantHousingUnitsAllOtherVacants"
  end

  create_table "states", force: true do |t|
    t.string "StateFullName"
    t.string "StateAbbreviation"
  end

  add_index "states", ["StateAbbreviation"], name: "index_states_on_StateAbbreviation", using: :btree
  add_index "states", ["StateFullName"], name: "index_states_on_StateFullName", using: :btree

  create_table "zip_codes", primary_key: "ZipCode", force: true do |t|
    t.float   "Longitude"
    t.float   "Latitude"
    t.integer "ElevationAverageFeet"
    t.integer "Population"
    t.integer "WhitePopulation"
    t.integer "BlackPopulation"
    t.integer "HispanicPopulation"
    t.integer "AsianPopulation"
    t.integer "HawaiianPopulation"
    t.integer "IndianPopulation"
    t.integer "OtherPopulation"
    t.integer "MalePopulation"
    t.integer "FemalePopulation"
    t.float   "MedianAge"
    t.float   "MedianAgeMale"
    t.float   "MedianAgeFemale"
    t.float   "HouseholdsPerZipCode"
    t.float   "PersonsPerHousehold"
    t.float   "AverageHouseValue"
    t.float   "IncomePerHousehold"
    t.float   "IncomeBelowPoverty"
    t.float   "IncomeLessThan25"
    t.float   "IncomeBetween25to50"
    t.float   "IncomeBetween50to100"
    t.float   "IncomeBetween100to200"
    t.float   "IncomeGreater200"
    t.float   "EducationHighSchoolGraduate"
    t.float   "EducationBachelorOrGreater"
    t.integer "state_id"
    t.string  "AreaCode"
    t.string  "County"
    t.string  "CountyFIPSCode"
    t.string  "StateFIPSCode"
    t.integer "TimeZone"
    t.boolean "IsDayLightSaving"
    t.boolean "IsZipCodeMultiCounty"
    t.string  "USRegion"
    t.string  "USDivision"
    t.string  "MSA"
    t.string  "MSAName"
    t.string  "PMSA"
    t.string  "PMSAName"
    t.string  "CSA"
    t.string  "CSAName"
    t.string  "CBSA"
    t.string  "CBSAName"
    t.string  "CBSADivision"
    t.string  "CBSAStatisticType"
    t.string  "CBSADivisionName"
    t.integer "TotalNumberOfBusinesses"
    t.integer "TotalNumberEmployees"
    t.integer "FirstQuarterPayroll"
    t.integer "AnnualPayroll"
    t.integer "ViolentCrime"
    t.integer "MurderAndManslaughter"
    t.integer "ForcibleRape"
    t.integer "Robbery"
    t.integer "AggravatedAssault"
    t.integer "PropertyCrime"
    t.integer "Burglary"
    t.integer "LarcenyTheft"
    t.integer "MotorVehicleTheft"
    t.integer "Arson"
    t.integer "GrowthRank"
    t.integer "GrowthHousingUnits2009"
    t.integer "GrowthHousingUnits2010"
    t.integer "GrowthIncreaseNumber"
    t.float   "GrowthIncreasePercentage"
    t.integer "DeliveryResidential"
    t.integer "DeliveryBusiness"
    t.integer "DeliveryTotal"
    t.float   "LandArea"
    t.float   "WaterArea"
    t.integer "PopulationEstimate"
    t.integer "SFDU"
    t.integer "MFDU"
    t.integer "PopulationUnder5"
    t.integer "Population5to9"
    t.integer "Population10to14"
    t.integer "Population15to19"
    t.integer "Population20to24"
    t.integer "Population25to29"
    t.integer "Population30to34"
    t.integer "Population35to39"
    t.integer "Population40to44"
    t.integer "Population45to49"
    t.integer "Population50to54"
    t.integer "Population55to59"
    t.integer "Population60to64"
    t.integer "Population65to69"
    t.integer "Population70to74"
    t.integer "Population75to79"
    t.integer "Population80to84"
    t.integer "Population85Plus"
    t.float   "PopulationMedian"
    t.integer "Population16Plus"
    t.integer "Population18Plus"
    t.integer "Population21Plus"
    t.integer "Population62Plus"
    t.integer "Population65Plus"
    t.integer "PopulationMale"
    t.integer "PopulationMaleUnder5"
    t.integer "PopulationMale5to9"
    t.integer "PopulationMale10to14"
    t.integer "PopulationMale15to19"
    t.integer "PopulationMale20to24"
    t.integer "PopulationMale25to29"
    t.integer "PopulationMale30to34"
    t.integer "PopulationMale35to39"
    t.integer "PopulationMale40to44"
    t.integer "PopulationMale45to49"
    t.integer "PopulationMale50to54"
    t.integer "PopulationMale55to59"
    t.integer "PopulationMale60to64"
    t.integer "PopulationMale65to69"
    t.integer "PopulationMale70to74"
    t.integer "PopulationMale75to79"
    t.integer "PopulationMale80to84"
    t.integer "PopulationMale85Plus"
    t.float   "PopulationMaleMedian"
    t.integer "PopulationMale16Plus"
    t.integer "PopulationMale18Plus"
    t.integer "PopulationMale21Plus"
    t.integer "PopulationMale62Plus"
    t.integer "PopulationMale65Plus"
    t.integer "PopulationFemale"
    t.integer "PopulationFemaleUnder5"
    t.integer "PopulationFemale5to9"
    t.integer "PopulationFemale10to14"
    t.integer "PopulationFemale15to19"
    t.integer "PopulationFemale20to24"
    t.integer "PopulationFemale25to29"
    t.integer "PopulationFemale30to34"
    t.integer "PopulationFemale35to39"
    t.integer "PopulationFemale40to44"
    t.integer "PopulationFemale45to49"
    t.integer "PopulationFemale50to54"
    t.integer "PopulationFemale55to59"
    t.integer "PopulationFemale60to64"
    t.integer "PopulationFemale65to69"
    t.integer "PopulationFemale70to74"
    t.integer "PopulationFemale75to79"
    t.integer "PopulationFemale80to84"
    t.integer "PopulationFemale85Plus"
    t.float   "PopulationFemaleMedian"
    t.integer "PopulationFemale16Plus"
    t.integer "PopulationFemale18Plus"
    t.integer "PopulationFemale21Plus"
    t.integer "PopulationFemale62Plus"
    t.integer "PopulationFemale65Plus"
    t.float   "AverageHouseholdSize"
    t.float   "AverageFamilySize"
    t.integer "TotalHouseholds"
    t.integer "FamilyHouseholds"
    t.integer "FamilyHouseholdsWithChildrenUnder18"
    t.integer "FamilyHouseholdsHusbandWifeFamily"
    t.integer "FamilyHouseholdsHusbandWifeFamilyChildrenUnder18"
    t.integer "FamilyHouseholdsMaleNoWife"
    t.integer "FamilyHouseholdsMaleNoWifeChildrenUnder18"
    t.integer "FamilyHouseholdFemaleNoHusband"
    t.integer "FamilyHouseholdFemaleNoHusbandChildrenUnder18"
    t.integer "NonFamilyHouseholds"
    t.integer "NonFamilyHouseholdsLivingAlone"
    t.integer "NonFamilyHouseholdsLivingAloneMale"
    t.integer "NonFamilyHouseholdsLivingAloneMale65plus"
    t.integer "NonFamilyHouseholdsLivingAloneFemale"
    t.integer "NonFamilyHouseholdsLivingAloneFemale65plus"
    t.integer "HouseholdsWithIndividualsUnder18"
    t.integer "HouseholdsWithIndividuals65plus"
    t.integer "TotalHousingUnits"
    t.integer "OccupiedHousingUnits"
    t.integer "VacantHousingUnits"
    t.integer "VacantHousingUnitsForRent"
    t.integer "VacantHousingUnitsRentedNotOccupied"
    t.integer "VacantHousingUnitsForSale"
    t.integer "VacantHousingUnitsSoldNotOccupied"
    t.integer "VacantHousingUnitsForSeasonalOccasionalUse"
    t.integer "VacantHousingUnitsAllOtherVacants"
  end

  add_index "zip_codes", ["Latitude"], name: "index_zip_codes_on_Latitude", using: :btree
  add_index "zip_codes", ["Longitude"], name: "index_zip_codes_on_Longitude", using: :btree

end
